### ISSUE TITLE
Sample #'s not matched with supplementary

### ISSUE THREAD

**Issue by tcikezu** [samuel-marsh/Marsh_et-al_2022_scRNAseq_Dissociation_Artifacts#1]
Hi Samuel, thank you for sharing all your analyses on github.

Supplementary table 1 lists mice as samples 1-12, the first six corresponding to batch 1 and second six corresponding to batch 2.
However the samples in [GSE152183](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152183) are listed as {Dounce,Miltenyi}_IN_sample_0{1..6} and {Dounce,Miltenyi}_NO__sample_0{1..6}

Please clarify which samples are which. Thank you!

**Comment by samuel-marsh** [comment]
Hi,

Apologies for not seeing this sooner.  I will get back to you on Monday but just wanted to quickly let you know I’ve seen this and will get back to you.

Best,
Sam

**Comment by samuel-marsh** [comment]
Hi,

Apologies for the confusion.  The order of the NCBI GEO record sample numbers starting with GSM4605687-GSM4605698 is the 1-12 order from SI Table 1.

Best,
Sam
